class CategoryModel {
  const CategoryModel(
    this.name,
    this.year,
  );
  final int year;
  final String name;

  static Map<int, List<CategoryModel>> get tableByYear {
    final Map<int, List<CategoryModel>> table = {};
    for (var movie in movies) {
      if (table.containsKey(movie.year)) {
        table[movie.year] = [movie, ...table[movie.year]!];
      } else {
        table[movie.year] = [movie];
      }
    }
    return table;
  }

  static List<CategoryModel> get movies => [
        const CategoryModel('Парк юрского периода', 1993),
        const CategoryModel('Король Лев', 1994),
        const CategoryModel('День независимости', 1996),
        const CategoryModel('Титаник', 1997),
        const CategoryModel('Звёздные войны. Эпизод I: Скрытая угроза', 1999),
        const CategoryModel('Гарри Поттер и философский камень', 2001),
        const CategoryModel('Властелин колец: Братство Кольца', 2001),
        const CategoryModel('Властелин колец: Две крепости', 2002),
        const CategoryModel('Гарри Поттер и Тайная комната', 2002),
        const CategoryModel('Человек-паук', 2002),
        const CategoryModel('Властелин колец: Возвращение короля', 2003),
        const CategoryModel('В поисках Немо', 2003),
        const CategoryModel('Шрек 2', 2004),
        const CategoryModel('Гарри Поттер и Кубок огня', 2005),
        const CategoryModel('Звёздные войны. Эпизод III: Месть ситхов', 2005),
        const CategoryModel('Пираты Карибского моря: Сундук мертвеца', 2006),
        const CategoryModel('Пираты Карибского моря: На краю света', 2007),
        const CategoryModel('Гарри Поттер и Орден Феникса', 2007),
        const CategoryModel('Человек-паук 3: Враг в отражении', 2007),
        const CategoryModel('Шрек Третий', 2007),
        const CategoryModel('Тёмный рыцарь', 2008),
        const CategoryModel('Аватар', 2009),
        const CategoryModel('Гарри Поттер и Принц-полукровка', 2009),
        const CategoryModel('Ледниковый период 3: Эра динозавров', 2009),
        const CategoryModel('Трансформеры: Месть падших', 2009),
        const CategoryModel('История игрушек: Большой побег', 2010),
        const CategoryModel('Алиса в Стране чудес', 2010),
        const CategoryModel('Гарри Поттер и Дары Смерти. Часть 1', 2010),
        const CategoryModel('Начало', 2010),
        const CategoryModel('Гарри Поттер и Дары Смерти. Часть 2', 2011),
        const CategoryModel('Трансформеры 3: Тёмная сторона Луны', 2011),
        const CategoryModel(
            'Пираты Карибского моря: На странных берегах', 2011),
        const CategoryModel('Мстители', 2012),
        const CategoryModel('007: Координаты «Скайфолл»', 2012),
        const CategoryModel('Тёмный рыцарь: Возрождение легенды', 2012),
        const CategoryModel('Хоббит: Нежданное путешествие', 2012),
        const CategoryModel('Ледниковый период 4: Континентальный дрейф', 2012),
        const CategoryModel('Сумерки. Сага: Рассвет — Часть 2', 2012),
        const CategoryModel('Холодное сердце', 2013),
        const CategoryModel('Железный человек 3', 2013),
        const CategoryModel('Гадкий я 2', 2013),
        const CategoryModel('Хоббит: Пустошь Смауга', 2013),
        const CategoryModel('Голодные игры: И вспыхнет пламя', 2013),
        const CategoryModel('Трансформеры: Эпоха истребления', 2014),
        const CategoryModel('Хоббит: Битва пяти воинств', 2014),
        const CategoryModel('Звёздные войны: Пробуждение силы', 2015),
        const CategoryModel('Мир юрского периода', 2015),
        const CategoryModel('Форсаж 7', 2015),
        const CategoryModel('Мстители: Эра Альтрона', 2015),
        const CategoryModel('Миньоны', 2015),
        const CategoryModel('007: Спектр', 2015),
        const CategoryModel('Головоломка', 2015),
        const CategoryModel('Первый мститель: Противостояние', 2016),
        const CategoryModel('Изгой-один. Звёздные войны: Истории', 2016),
        const CategoryModel('В поисках Дори', 2016),
        const CategoryModel('Зверополис', 2016),
        const CategoryModel('Книга джунглей', 2016),
        const CategoryModel('Тайная жизнь домашних животных', 2016),
        const CategoryModel(
            'Бэтмен против Супермена: На заре справедливости', 2016),
        const CategoryModel('Фантастические твари и где они обитают', 2016),
        const CategoryModel('Звёздные войны: Последние джедаи', 2017),
        const CategoryModel('Красавица и чудовище', 2017),
        const CategoryModel('Форсаж 8', 2017),
        const CategoryModel('Гадкий я 3', 2017),
        const CategoryModel('Джуманджи: Зов джунглей', 2017),
        const CategoryModel('Человек-паук: Возвращение домой', 2017),
        const CategoryModel('Война волков 2', 2017),
        const CategoryModel('Стражи Галактики. Часть 2', 2017),
        const CategoryModel('Тор: Рагнарёк', 2017),
        const CategoryModel('Чудо-женщина', 2017),
        const CategoryModel('Тайна Коко', 2017),
        const CategoryModel('Мстители: Война бесконечности', 2018),
        const CategoryModel('Чёрная пантера', 2018),
        const CategoryModel('Мир юрского периода 2', 2018),
        const CategoryModel('Суперсемейка 2', 2018),
        const CategoryModel('Аквамен', 2018),
        const CategoryModel('Богемская рапсодия', 2018),
        const CategoryModel('Веном', 2018),
        const CategoryModel('Мстители: Финал', 2019),
        const CategoryModel('Король Лев', 2019),
        const CategoryModel('Холодное сердце 2', 2019),
        const CategoryModel('Человек-паук: Вдали от дома', 2019),
        const CategoryModel('Капитан Марвел', 2019),
        const CategoryModel('Звёздные войны: Скайуокер. Восход', 2019),
        const CategoryModel('Джокер', 2019),
        const CategoryModel('История игрушек 4', 2019),
        const CategoryModel('Аладдин', 2019),
        const CategoryModel('Джуманджи: Новый уровень', 2019),
        const CategoryModel('Человек-паук: Нет пути домой', 2021),
        const CategoryModel('Битва при Чосинском водохранилище', 2021),
        const CategoryModel('Привет, мам', 2021),
        const CategoryModel('Аватар: Путь воды', 2022),
        const CategoryModel('Топ Ган: Мэверик', 2022),
        const CategoryModel('Мир юрского периода: Господство', 2022),
        const CategoryModel('Доктор Стрэндж: В мультивселенной безумия', 2022),
        const CategoryModel('Миньоны: Грювитация', 2022),
        const CategoryModel('Чёрная пантера: Ваканда навеки', 2022),
        const CategoryModel('Братья Супер Марио в кино', 2023),
        const CategoryModel('Барби', 2023),
        const CategoryModel('Стражи Галактики. Часть 3', 2023),
      ];
}
